script: 'bundle exec rspec spec'
language: ruby
notifications:
  email:
    - abf@openmandriva.org
    - avokhmin@gmail.com
branches:
  only:
    - master
rvm:
  - 2.2.3
before_script:
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:create db:schema:load
